name: deploy to azure function
on:
  push:
    branches: [ "main" ]
env:
  AZURE_FUNCTIONAPP_NAME: cloudmailin-dida365-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: 'Set up Go'
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build .
      
    - name: 'Deploy to Azure'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      